
from midgard.site_info import site_info
import pytest

@pytest.fixture
def sinex_data():
    """ A dictionary with data parsed from a sinex file
    """
    data = dict()
    
    data["zimm"] = {'site_id': {'site_code': 'zimm',
              'point_code': 'A',
              'domes': '14001',
              'marker': 'M004',
              'obs_code': 'P',
              'description': 'Zimmerwald, Switzerlan',
              'approx_lon': 7.465277777777778,
              'approx_lat': 46.87708333333334,
              'approx_height': 956.4},
             'site_receiver': [{'site_code': 'zimm',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(1993, 5, 1, 0, 0),
               'end_time': datetime.datetime(1997, 8, 6, 0, 0),
               'receiver_type': 'TRIMBLE 4000SSE',
               'serial_number': '3310A',
               'firmware': '6.12'},
              {'site_code': 'zimm',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(1997, 8, 6, 0, 0),
               'end_time': datetime.datetime(1999, 8, 16, 0, 0),
               'receiver_type': 'TRIMBLE 4000SSI',
               'serial_number': '3310A',
               'firmware': '7.25'},
              {'site_code': 'zimm',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(1999, 8, 16, 0, 0),
               'end_time': datetime.datetime(2003, 8, 12, 14, 0),
               'receiver_type': 'TRIMBLE 4000SSI',
               'serial_number': '3310A',
               'firmware': '7.29'},
              {'site_code': 'zimm',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2003, 8, 12, 14, 0),
               'end_time': datetime.datetime(2006, 2, 22, 8, 0),
               'receiver_type': 'TRIMBLE 4700',
               'serial_number': '20224',
               'firmware': 'Nav  1.30 /'},
              {'site_code': 'zimm',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2006, 2, 22, 14, 0),
               'end_time': datetime.datetime(2008, 4, 1, 14, 10),
               'receiver_type': 'TRIMBLE NETRS',
               'serial_number': '45262',
               'firmware': 'Nav  1.15 /'},
              {'site_code': 'zimm',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2008, 4, 1, 14, 10),
               'end_time': datetime.datetime(2014, 5, 7, 7, 20),
               'receiver_type': 'TRIMBLE NETRS',
               'serial_number': '45262',
               'firmware': 'Nav  1.20'},
              {'site_code': 'zimm',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2014, 5, 7, 7, 20),
               'end_time': datetime.datetime(2015, 4, 27, 7, 15),
               'receiver_type': 'TRIMBLE NETRS',
               'serial_number': '45262',
               'firmware': '1.32'},
              {'site_code': 'zimm',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2015, 4, 27, 7, 15),
               'end_time': datetime.datetime(2015, 6, 19, 6, 30),
               'receiver_type': 'TRIMBLE NETR9',
               'serial_number': '5429R',
               'firmware': '4.85'},
              {'site_code': 'zimm',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2015, 6, 19, 6, 30),
               'end_time': datetime.datetime(2015, 8, 11, 8, 45),
               'receiver_type': 'TRIMBLE NETR9',
               'serial_number': '5429R',
               'firmware': '5.01'},
              {'site_code': 'zimm',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2015, 8, 11, 8, 45),
               'end_time': datetime.datetime(2015, 12, 16, 9, 20),
               'receiver_type': 'TRIMBLE NETR9',
               'serial_number': '5429R',
               'firmware': '5.03'},
              {'site_code': 'zimm',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2015, 12, 16, 9, 20),
               'end_time': datetime.datetime(2017, 2, 6, 8, 20),
               'receiver_type': 'TRIMBLE NETR9',
               'serial_number': '5429R',
               'firmware': '5.10'},
              {'site_code': 'zimm',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2017, 2, 6, 8, 20),
               'end_time': datetime.datetime(2017, 2, 8, 11, 8),
               'receiver_type': 'TRIMBLE NETR9',
               'serial_number': '5429R',
               'firmware': '5.20'},
              {'site_code': 'zimm',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2017, 2, 8, 11, 8),
               'end_time': datetime.datetime(2017, 4, 11, 12, 5),
               'receiver_type': 'TRIMBLE NETR9',
               'serial_number': '5429R',
               'firmware': '5.10'},
              {'site_code': 'zimm',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2017, 4, 11, 12, 5),
               'end_time': datetime.datetime(2018, 12, 18, 9, 45),
               'receiver_type': 'TRIMBLE NETR9',
               'serial_number': '5429R',
               'firmware': '5.22'},
              {'site_code': 'zimm',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2018, 12, 18, 9, 45),
               'end_time': datetime.datetime(2020, 6, 8, 7, 15),
               'receiver_type': 'TRIMBLE NETR9',
               'serial_number': '5429R',
               'firmware': '5.37'},
              {'site_code': 'zimm',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2020, 6, 8, 7, 15),
               'end_time': None,
               'receiver_type': 'TRIMBLE NETR9',
               'serial_number': '5429R',
               'firmware': '5.45'}],
             'site_antenna': [{'site_code': 'zimm',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(1993, 5, 1, 0, 0),
               'end_time': datetime.datetime(1998, 11, 6, 0, 0),
               'antenna_type': 'TRM14532.00',
               'serial_number': '3311A',
               'radome_type': 'NONE'},
              {'site_code': 'zimm',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(1998, 11, 6, 0, 0),
               'end_time': None,
               'antenna_type': 'TRM29659.00',
               'serial_number': '99390',
               'radome_type': 'NONE'}],
             'site_eccentricity': [{'site_code': 'zimm',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(1993, 5, 1, 0, 0),
               'end_time': None,
               'vector_type': 'UNE',
               'vector_1': 0.0,
               'vector_2': 0.0,
               'vector_3': 0.0}]}
    
    data["hrao"] = {'site_id': {'site_code': 'hrao',
              'point_code': 'A',
              'domes': '30302',
              'marker': 'M004',
              'obs_code': 'P',
              'description': 'Krugersdorp, South Afr',
              'approx_lon': 27.686972222222224,
              'approx_lat': -25.89011111111111,
              'approx_height': 1414.3},
             'site_receiver': [{'site_code': 'hrao',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(1996, 9, 5, 0, 0),
               'end_time': datetime.datetime(1998, 1, 14, 0, 0),
               'receiver_type': 'ROGUE SNR-8000',
               'serial_number': 'T365',
               'firmware': '3.2 link 03'},
              {'site_code': 'hrao',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(1998, 1, 14, 0, 0),
               'end_time': datetime.datetime(1999, 5, 25, 12, 30),
               'receiver_type': 'ROGUE SNR-12 RM',
               'serial_number': '254',
               'firmware': '3.2.32.4'},
              {'site_code': 'hrao',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(1999, 5, 25, 12, 30),
               'end_time': datetime.datetime(2000, 4, 16, 0, 0),
               'receiver_type': 'ROGUE SNR-12 RM',
               'serial_number': '254',
               'firmware': '3.2.32.8'},
              {'site_code': 'hrao',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2000, 4, 26, 12, 30),
               'end_time': datetime.datetime(2006, 12, 28, 0, 0),
               'receiver_type': 'ASHTECH Z-XII3',
               'serial_number': 'LP019',
               'firmware': 'CC00 1s soc'},
              {'site_code': 'hrao',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2007, 4, 26, 0, 0),
               'end_time': datetime.datetime(2007, 12, 11, 16, 22),
               'receiver_type': 'ASHTECH UZ-12',
               'serial_number': 'ZR520',
               'firmware': 'CQ00'},
              {'site_code': 'hrao',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2008, 2, 14, 9, 0),
               'end_time': datetime.datetime(2009, 1, 10, 10, 59),
               'receiver_type': 'ASHTECH UZ-12',
               'serial_number': 'ZR220',
               'firmware': 'CQ00'},
              {'site_code': 'hrao',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2009, 1, 15, 0, 0),
               'end_time': datetime.datetime(2012, 3, 30, 17, 15),
               'receiver_type': 'ASHTECH UZ-12',
               'serial_number': 'UC120',
               'firmware': 'CN00'},
              {'site_code': 'hrao',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2012, 4, 12, 0, 0),
               'end_time': datetime.datetime(2014, 7, 23, 1, 30),
               'receiver_type': 'ASHTECH Z-XII3',
               'serial_number': 'LP008',
               'firmware': 'CD00'},
              {'site_code': 'hrao',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2014, 7, 23, 1, 35),
               'end_time': datetime.datetime(2014, 8, 21, 16, 39),
               'receiver_type': 'JAVAD TRE_G3TH DELTA',
               'serial_number': '01707',
               'firmware': '3.5.5'},
              {'site_code': 'hrao',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2014, 8, 21, 16, 40),
               'end_time': datetime.datetime(2014, 10, 22, 22, 0),
               'receiver_type': 'JAVAD TRE_G3TH DELTA',
               'serial_number': '01707',
               'firmware': '3.5.6'},
              {'site_code': 'hrao',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2014, 10, 22, 22, 15),
               'end_time': datetime.datetime(2015, 1, 21, 20, 39),
               'receiver_type': 'JAVAD TRE_G3TH DELTA',
               'serial_number': '01707',
               'firmware': '3.5.7b0'},
              {'site_code': 'hrao',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2015, 1, 21, 20, 40),
               'end_time': datetime.datetime(2016, 2, 19, 17, 5),
               'receiver_type': 'JAVAD TRE_G3TH DELTA',
               'serial_number': '01707',
               'firmware': '3.5.8b0-12-'},
              {'site_code': 'hrao',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2016, 2, 19, 17, 15),
               'end_time': datetime.datetime(2018, 4, 10, 17, 0),
               'receiver_type': 'JAVAD TRE_G3TH DELTA',
               'serial_number': '01707',
               'firmware': '3.6.4'},
              {'site_code': 'hrao',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2018, 4, 10, 17, 15),
               'end_time': datetime.datetime(2018, 12, 27, 17, 11),
               'receiver_type': 'JAVAD TRE_G3TH DELTA',
               'serial_number': '01707',
               'firmware': '3.7.2'},
              {'site_code': 'hrao',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2018, 12, 27, 17, 15),
               'end_time': datetime.datetime(2019, 5, 23, 22, 51),
               'receiver_type': 'JAVAD TRE_G3TH DELTA',
               'serial_number': '01707',
               'firmware': '3.7.4'},
              {'site_code': 'hrao',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2019, 5, 23, 22, 51),
               'end_time': datetime.datetime(2020, 3, 24, 20, 52),
               'receiver_type': 'JAVAD TRE_G3TH DELTA',
               'serial_number': '01707',
               'firmware': '3.7.6'},
              {'site_code': 'hrao',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2020, 3, 24, 20, 52),
               'end_time': None,
               'receiver_type': 'JAVAD TRE_G3TH DELTA',
               'serial_number': '01707',
               'firmware': '3.7.9'}],
             'site_antenna': [{'site_code': 'hrao',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(1996, 9, 5, 0, 0),
               'end_time': datetime.datetime(1998, 1, 14, 0, 0),
               'antenna_type': 'AOAD/M_T',
               'serial_number': '200',
               'radome_type': 'NONE'},
              {'site_code': 'hrao',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(1998, 1, 14, 0, 0),
               'end_time': datetime.datetime(1999, 2, 20, 0, 0),
               'antenna_type': 'AOAD/M_T',
               'serial_number': '201',
               'radome_type': 'NONE'},
              {'site_code': 'hrao',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(1999, 2, 20, 0, 0),
               'end_time': datetime.datetime(1999, 7, 13, 7, 0),
               'antenna_type': 'AOAD/M_T',
               'serial_number': '127',
               'radome_type': 'NONE'},
              {'site_code': 'hrao',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(1999, 7, 13, 7, 0),
               'end_time': datetime.datetime(2003, 10, 17, 8, 55),
               'antenna_type': 'AOAD/M_T',
               'serial_number': '201',
               'radome_type': 'NONE'},
              {'site_code': 'hrao',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2003, 10, 17, 9, 0),
               'end_time': datetime.datetime(2004, 11, 19, 10, 30),
               'antenna_type': 'AOAD/M_T',
               'serial_number': '388',
               'radome_type': 'NONE'},
              {'site_code': 'hrao',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2004, 11, 19, 10, 30),
               'end_time': datetime.datetime(2005, 4, 24, 0, 0),
               'antenna_type': 'ASH701945C_M',
               'serial_number': 'CR520',
               'radome_type': 'NONE'},
              {'site_code': 'hrao',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2005, 5, 3, 9, 0),
               'end_time': datetime.datetime(2006, 2, 13, 12, 30),
               'antenna_type': 'ASH701945C_M',
               'serial_number': 'CR520',
               'radome_type': 'NONE'},
              {'site_code': 'hrao',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2006, 2, 14, 10, 30),
               'end_time': datetime.datetime(2006, 2, 21, 18, 0),
               'antenna_type': 'ASH701945C_M',
               'serial_number': 'CR620',
               'radome_type': 'NONE'},
              {'site_code': 'hrao',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2006, 2, 23, 0, 0),
               'end_time': datetime.datetime(2006, 12, 28, 0, 0),
               'antenna_type': 'ASH701945C_M',
               'serial_number': 'CR519',
               'radome_type': 'NONE'},
              {'site_code': 'hrao',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2007, 4, 26, 0, 0),
               'end_time': datetime.datetime(2007, 12, 11, 16, 22),
               'antenna_type': 'ASH701945C_M',
               'serial_number': 'CR520',
               'radome_type': 'NONE'},
              {'site_code': 'hrao',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(2008, 2, 14, 9, 0),
               'end_time': None,
               'antenna_type': 'ASH701945E_M',
               'serial_number': 'CR620',
               'radome_type': 'NONE'}],
             'site_eccentricity': [{'site_code': 'hrao',
               'point_code': 'A',
               'soln': '----',
               'obs_code': 'P',
               'start_time': datetime.datetime(1996, 9, 5, 0, 0),
               'end_time': None,
               'vector_type': 'UNE',
               'vector_1': 0.0814,
               'vector_2': 0.0,
               'vector_3': 0.0}]}


def test_site_info_sinex():
    site_info.SiteInfo.get_history("snx", "zimm", sinex_data(), "path/to/sinex")
    site_info.SiteInfo.get_history("snx", "zimm,hrao", sinex_data(), "path/to/sinex")
    site_info.SiteInfo.get_history("snx", ["zimm","hrao"], sinex_data(), "path/to/sinex")
    from datetime import datetime
    SiteInfo.get("snx", sta, datetime.now(), source_data, source_path=p.file_path)
    
def test_site_info_sesite()
    from datetime import datetime
    data2 = SiteInfo.get("sesite", stations, datetime.now(), api, source_path=sesite_api_url):
    